### PR TITLE
Fix internet based personalities (gpt4internet & low)

### PR DESCRIPTION
**Pull request by ba2512005**
Resolved issues listed here https://github.com/ParisNeo/lollms-webui/issues/480

The rest of the personalities still need to be tested. 

The most useful one that I fixed was GPT4Internet.

### CODE REVIEW

**Comment by ba2512005** [comment]
@ParisNeo Please review and approve.

Also please look at the rest of the personalities being called by the old run_workflow definitions and update.

**Comment by ParisNeo** [comment]
Thanks for your contribution

**Comment by ParisNeo** [comment]
I will update the old personas. With the new format.

**Comment by ba2512005** [comment]
> I will update the old personas. With the new format.

You're welcome

@ParisNeo I just looked through the code and found 3 that need to be changed:
Thinking_methodologies/tree_of_thoughts (which you already did)

Additionally:
Thinking_methodologies/chain_of_thoughts
data/database_maker
data/text2bulletpoints

**Pull request merged**
